export const site = {
  name: "St. Patrick's Society Hong Kong",
  shortName: "St. Patrick's HK",
  tagline: "Connect. Celebrate. Contribute.",
  founded: 1931,
  description:
    "Hong Kong's Irish community society since 1931 — a place to connect, celebrate Irish culture, and contribute to local causes.",
  url: "https://www.stpatrickshk.com",
  email: "info@stpatrickshk.com",
  galaAlbumUrl: "https://photos.app.goo.gl/VKP8xZhejEpivhL6A",
  social: {
    facebook: "https://www.facebook.com/StPatricksSocietyHongKong/",
    instagram: "https://www.instagram.com/stpatrickshk/",
    x: "https://twitter.com/StPatricks_HK",
  },
  membership: {
    name: "Green Card",
    price: "HK$888",
    term: "lifetime",
  },
} as const;

export const nav = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/events", label: "Events" },
  { href: "/gala", label: "Gala" },
  { href: "/contact", label: "Contact" },
] as const;

export const committee = [
  { name: "John Alan O'Sullivan", role: "President" },
  { name: "Marilouise Hughes-King", role: "Committee Secretary" },
  { name: "Declan Doran", role: "Treasurer" },
  { name: "Monica Dolan", role: "Committee Member" },
  { name: "Marie-Claire Mulligan", role: "Committee Member" },
  { name: "Mark Rawson", role: "Committee Member" },
] as const;

export const pastPresidents = [
  { year: "1931", name: "Sir Joseph Kemp, C.B.E." },
  { year: "1932", name: "Col. C. D. Myles, O.B.E." },
  { year: "1933", name: "Prof. F. A. Redmond" },
  { year: "1934", name: "Dr. W. B. A. Moore, O.B.E." },
  { year: "1935", name: "Mr. B. H. C. Hallowes" },
  { year: "1936", name: "Mr. F. P. R. James" },
  { year: "1937", name: "Sir Ernest Williams" },
  { year: "1938", name: "Dr. G. W. Pope" },
  { year: "1939", name: "Mr. C. G. Perdue" },
  { year: "1940", name: "Mr. J. C. M. Grenham, M.B.E." },
  { year: "1941", name: "Hon. C. E. M. Terry, O.B.E." },
  { year: "1942", name: "Mr. P. J. A. Hamilton" },
  { year: "1947", name: "Dr. The Hon. P. J. Fehily, O.B.E." },
  { year: "1948", name: "Mr. W. La B. Sparrow" },
  { year: "1949", name: "Hon. D. J. S. Crozier, C.M.G." },
  { year: "1950", name: "Mr. F. G. Maunder" },
  { year: "1951", name: "Sir John Griffin, Q.C." },
  { year: "1952", name: "Mr. E. R. Farrell" },
  { year: "1953", name: "Mr. F. Shanks, O.B.E." },
  { year: "1954", name: "Dr. J. H. McElney" },
  { year: "1955", name: "Miss Elma Kelly" },
  { year: "1956", name: "Hon. H. D. M. Barton, M.B.E." },
  { year: "1957", name: "Mr. B. T. Flanagan" },
  { year: "1958", name: "Professor B. Harrison" },
  { year: "1959", name: "Dr. A. W. Dawson-Grove, M.B.E." },
  { year: "1960", name: "Mr. J. A. Fox" },
  { year: "1961", name: "Sir Michael Hogan, Kt., C.M.G." },
  { year: "1962", name: "Professor Sean Mackey, O.B.E." },
  { year: "1963", name: "Mr. J. F. Lindsay" },
  { year: "1964", name: "Mr. Justice B. Jennings" },
  { year: "1965", name: "Prof. E. O’F. Walsh" },
  { year: "1966", name: "Mr. J. A. O’Hanrahan" },
  { year: "1967", name: "Hon. C. E. M. Terry, O.B.E., O.St.J., J.P." },
  { year: "1968", name: "Mr. D. R. Bland" },
  { year: "1969", name: "Mr. G. I. McCabe" },
  { year: "1970", name: "Mr. T. B. P. O’Connell" },
  { year: "1971", name: "Mr. B. F. Slevin, Q.P.M., J.P." },
  { year: "1972", name: "Mr. K. B. O’Sullivan" },
  { year: "1973", name: "Prof. Sean Raferty" },
  { year: "1974", name: "Mr. L. Power, Q.P.M." },
  { year: "1975", name: "Mr. S. G. Elliott" },
  { year: "1976", name: "Mr. J. P. MacMahon, C.P.M." },
  { year: "1977", name: "Mrs. B. M. M. Murray" },
  { year: "1978", name: "Mr. T. A. Fitzpatrick" },
  { year: "1979", name: "Mr. T. Frawley" },
  { year: "1980", name: "Mr. B. Keown" },
  { year: "1981", name: "Mr. McDermott" },
  { year: "1982", name: "Mr. H. Williams" },
  { year: "1983", name: "Mr. G. Fields" },
  { year: "1984", name: "Mr. B. Griffin" },
  { year: "1985", name: "Mrs. B. McKenzie" },
  { year: "1986", name: "Mr. D. Agnew" },
  { year: "1987", name: "Mr. J. R. P. Breen" },
  { year: "1988", name: "Mrs. E. Shannon" },
  { year: "1989", name: "Mr. J. N. McCaffrey" },
  { year: "1990", name: "Mr. A. Mackay" },
  { year: "1991", name: "Mr. P. Hurley" },
  { year: "1992", name: "Mr. P. McMahon" },
  { year: "1993", name: "Mr. G. McEnery" },
  { year: "1994", name: "Mr. Robert Farrell" },
  { year: "1995", name: "Ms. Molly Donoghue" },
  { year: "1996", name: "Mr. Dan Manning" },
  { year: "1997", name: "Ms. Fiona Loughrey" },
  { year: "1998", name: "Mr. Ian Candy" },
  { year: "1999", name: "Mrs. Thérèse Beresford" },
  { year: "2000", name: "Mr. Harry O’Neill" },
  { year: "2001", name: "Mr. Darach Haughey" },
  { year: "2002", name: "Mr. Tom Mulvey J.P." },
  { year: "2003", name: "Mr. Ronan Delaney" },
  { year: "2004", name: "Ms. Anne Noonan" },
  { year: "2005", name: "Mr. Ian Carroll" },
  { year: "2006", name: "Mrs. Orla Thomas" },
  { year: "2007", name: "Mr. Noel Smyth" },
  { year: "2008", name: "Ms. Dorraine Dempsey" },
  { year: "2009", name: "Mr. Damian McManamon" },
  { year: "2010", name: "Ms. Orla Gilroy" },
  { year: "2011", name: "Mr. Ian Lawlor" },
  { year: "2012–2013", name: "Comdt. Graeme Martin" },
  { year: "2014", name: "Ms. Kayte Candy" },
  { year: "2015", name: "Mr. Noel Smyth" },
  { year: "2016", name: "Mrs. Lynne Mullholland-Ul" },
  { year: "2017", name: "Mr. Fergal Power" },
  { year: "2018–2019", name: "Mr. Mat Gallagher" },
  { year: "2020–2024", name: "Mrs. Marilouise Hughes-King" },
  { year: "2025", name: "Mr. John Alan O'Sullivan" },
] as const;

export const galleryAlbums: {
  title: string;
  date: string;
  href?: string;
  featured?: boolean;
}[] = [
  {
    title: "St. Patrick's Gala 2026",
    date: "14 March 2026",
    href: "https://photos.app.goo.gl/VKP8xZhejEpivhL6A",
    featured: true,
  },
  {
    title: "Emerald Gala Ball",
    date: "14 March 2025",
  },
  {
    title: "Irish Festival",
    date: "16–17 March 2024",
  },
  {
    title: "National Day wreath laying, Cenotaph",
    date: "16 March 2024",
  },
  {
    title: "St. Patrick's Day colouring competition",
    date: "March 2024",
  },
  {
    title: "Emerald Gala Ball",
    date: "11 March 2023",
  },
  {
    title: "Bloomsday Breakfast",
    date: "16 June 2021",
  },
  {
    title: "Annual Ball",
    date: "9 March 2019",
  },
  {
    title: "St. Patrick's Week festivities",
    date: "March 2019",
  },
] as const;
